server {
    listen       3000;
#     listen  [::]:80;
    server_name  localhost;

   location /api/v1/info {
        default_type application/json;
        set $current_time "$time_iso8601";

        return 200 '{"name": "Ronin Engineer", "date": "$current_time"}';
   }

   location /api/v1/health {
           default_type application/json;
           set $current_time "$time_iso8601";

           return 200 '{"status": "OK"}';
   }
}